config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources 'transactions', only: [:index, :create]
end

app/models/account.rb
class Account
  include ActiveModel::Model

  NODE_HOST = "go.nem.ninja"
  NODE_TIMEOUT = 10

  ADDRESS = "xxxxx"
  P_KEY = "xxxxx"

  def initialize
    @node = Nem::Node.new(host: NODE_HOST, timeout: NODE_TIMEOUT)
  end

  def find
    endpoint = Nem::Endpoint::Account.new(@node)
    endpoint.find(ADDRESS)
  end

  def transfers_all
    endpoint = Nem::Endpoint::Account.new(@node)
    transfers = endpoint.transfers_all(ADDRESS)

    result = []
    transfers.each do |t|
      # 簡潔にするため、マルチシグなどのトランザクションは省く
      next if t.type != 257
      result.push AccountTransaction.new(ADDRESS, t)
    end
    result
  end

  def transfer(params)
    endpoint = Nem::Endpoint::Transaction.new(@node)
    kp = Nem::Keypair.new(P_KEY)
    tx = Nem::Transaction::Transfer.new(params[:address], params[:amount].to_f, params[:message])
    req = Nem::Request::Announce.new(tx, kp)
    res = endpoint.announce(req)


    Rails.logger.debug("Message: #{res.message}")
    Rails.logger.debug("TransactionHash: #{res.transaction_hash}")
  end
end

app/models/account_transaction.rb
class AccountTransaction
  include ActiveModel::Model

  attr_reader :timestamp, :type, :amount, :fee, :message, :sender, :recipient

  def initialize(address, t)
    @timestamp = t.timestamp.to_time

    if t.recipient == address
      @type = "出金"
    else
      @type = "入金"
    end

    @amount = (t.amount.to_f / 1000000).to_s(:delimited)
    @fee = (t.fee.to_f / 1000000).to_s(:delimited)

    unless t.message.blank?
      case t.message.type
      when Nem::Model::Message::TYPE_PLAIN
        @message = [t.message.value].pack("H*").force_encoding("utf-8")
      when Nem::Model::Message::TYPE_ENCRYPTED
        @message = "[暗号化]"
      else
        @message = ""
      end
    end

    # signerに送信者の公開鍵が格納されている
    # @sender = endpoint.find_by_public_key(t.signer).address
    # @recipient = t.recipient
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    account = Account.new

    # 残高確認
    @account = account.find

    # 入出金履歴
    @transfers_all = account.transfers_all
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
  end

  def create
    # 送金
    account = Account.new
    account.transfer(transaction_params)
  end

  private

    def transaction_params
      params.require(:transaction).permit(:address, :amount, :message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def balance(b)
    b / 1000000.to_f
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/home/index.html.erb
<h1>NEM Wallet</h1>
<%= link_to "送金", :controller => "transactions", :action => "index" %>

<h2>アカウント</h2>
<table>
  <tbody>
    <tr>
      <td>アカウント：</td>
      <td><%= @account.address %></td>
    </tr>
    <tr>
      <td>残高(XEM)：</td>
      <td><%= balance(@account.balance) %> XEM</td>
    </tr>
    <tr>
      <td>重要度：</td>
      <td><%= @account.importance %></td>
    </tr>
  </tbody>
</table>

<h2>入出金履歴</h2>
<table border="1">
  <thead>
    <tr>
      <th>日時</th>
      <th>区分</th>
      <th>金額(XEM)</th>
      <th>手数料(XEM)</th>
      <th>メッセージ</th>
    </tr>
  </thead>

  <tbody>
    <% @transfers_all.each do |t| %>
      <tr>
        <td><%= t.timestamp %></td>
        <td><%= t.type %></td>
        <td><%= t.amount %></td>
        <td><%= t.fee %></td>
        <td><%= t.message %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NemRubyDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/transactions/index.html.erb
<h1>NEM Wallet</h1>
<%= link_to "HOME", :controller => "home", :action => "index" %>

<h2>送金</h2>
<%= form_with scope: :transaction, url: transactions_path do |f| %>
  <%= f.label :address, '宛先: ' %>
  <%= f.text_field :address, size: 100 %>
  <br/>

  <%= f.label :amount, '金額: ' %>
  <%= f.text_field :amount %>
  <br/>

  <%= f.label :message, 'メッセージ: ' %>
  <%= f.text_field :message, size: 100%>
  <br/>

  <%= f.button :submit %>
<% end %>